name: PeterdeGuzman

on: [push]



jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: install packages
      run: make install
    - name: lint
      run: make lint
    - name: test
      run: make test
    - name: format
      run: make format